# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d57ea61fc33d7c037976151bb9ea654815b5fd0b02007416647a9563e605210467ee52812e1ad2a5a489ef15088af741bb364d38d24182690185efd6d6c1b5f

test:
  secret_key_base: 8b47efd6f7b6ac56ee087a892445e8dc9ca226696f68e8e78a65f8dd0a5766cb153a9f3f2292039251e93e7a26e83095be8ed5bcb8508884924602204053176a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
