# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ef96a5200d6ecd8313ffde13242dd041bc5f6424b995258f8dfe5eb41c6aa7eb587cd42978abdb127402947ed561f1372d158a8fa332eb543dd4ad496f6185a

test:
  secret_key_base: 8372673419f9429b13f32f60d855d35be00df18c2055a5244cf493ddd81f5624ed18c54eb08f147e348aa7ae84ab76f60bbd4fbc2cfdacf5034afbc6550c3a80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
